---
- name: comment out source repositories
  replace:
    dest: /etc/apt/sources.list
    regexp: '^deb-src'
    replace: '#deb-src'

- name: base packages install
  apt:
    pkg:
      - lsof
      - jq
      - dosfstools
      - xfsprogs
      - ceph-common
      - docker.io
      - git
      - aptitude
      - python3-apt
    state: latest
    update_cache: yes
    install_recommends: no




