---
- hosts: rpi:nuc:!ceph
  become: yes
  roles:
    - pkg/common

- hosts: ceph
  become: yes
  roles:
    - pkg/common
    - pkg/ceph

- hosts: k8master:k8node
  become: yes
  roles:
    - pkg/kubernetes

- hosts: all
  become: yes
  roles:
    - pkg/maintenance
